name: Tests

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update packages
        run: |
          sudo apt-get update

      - name: Install docker
        run: |
          sudo snap install docker

      - name: Initialize LXD
        run: |
          sudo lxd init --auto

          sudo iptables -P FORWARD ACCEPT
          sudo sysctl net.ipv4.ip_forward=1

      - name: Install rockcraft
        run: |
          sudo snap install rockcraft --classic

      - name: Install yq
        run: |
          sudo snap install yq

      - name: Install tox
        run: |
          sudo apt-get install -y tox

      - name: Run Tox
        run: |
          cd multus && sudo tox
